version: '3.8'

services:
  angular-ionic-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8500:8500"
      - "8100:8100"
    volumes:
      - ./:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

