apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: livedocker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-blog
  template:
    metadata:
      labels:
        app: app-blog
    spec:
      containers:
      - name: blog
        image: localhost:5001/livedocker:1.0
        ports:
        - containerPort: 8100

---

apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: livedocker
spec:
  selector:
    app: app-blog
  ports:
  - port: 80
    targetPort: 8100
